import React from 'react';
import { FileText, Image } from 'lucide-react';
import { toPng, toSvg } from 'html-to-image';

export const LabReportExport = ({ results, variables, minterms, dontCares, mode = 'SOP' }) => {
  const accent = mode === 'POS' ? '#bc13fe' : '#00f3ff';
  const varNames = Array.from({ length: variables }, (_, i) => String.fromCharCode(65 + i));

  const generateLabReport = () => {
    const totalRows = Math.pow(2, variables);
    
    const reportContent = `
================================================================================
                    NOCTIS LOGIC SYNTHESIZER — LAB REPORT
================================================================================
Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}
Mode: ${mode} (${mode === 'SOP' ? 'Sum of Products — Optimize for logic 1s' : 'Product of Sums — Optimize for logic 0s'})

================================================================================
1. INPUT SPECIFICATION
================================================================================
  Variables:        ${variables} (${varNames.join(', ')})
  Total Rows:       ${totalRows}
  ${mode === 'SOP' ? 'Minterms (1s)' : 'Maxterms (0s)'}:    ${minterms.length > 0 ? minterms.join(', ') : 'None'}
  Don't Cares:      ${dontCares.length > 0 ? dontCares.join(', ') : 'None'}

================================================================================
2. ALGORITHM: QUINE-McCLUSKEY METHOD
================================================================================

2.1 INITIAL GROUPING (by number of 1s in binary)
${results.groupingSteps && results.groupingSteps[0] ? `
${Object.entries(results.groupingSteps[0]).map(([group, items]) => `
  Group ${group}:
${items.map(item => `    ${item.binary}  →  m(${item.terms.join(', ')})  ${item.combined ? '[Combined]' : '[Prime Implicant]'}`).join('\n')}`).join('\n')}` : '  No grouping data available.'}

2.2 ITERATIVE COMBINATION
${results.groupingSteps && results.groupingSteps.length > 1 ? results.groupingSteps.slice(1).map((step, idx) => `
  Stage ${idx + 2}:
${Object.entries(step).map(([group, items]) => `  Group ${group}: ${items.map(i => `${i.binary} (${i.terms.join(',')})${i.combined ? ' ✓' : ' [PI]'}`).join(', ')}`).join('\n')}`).join('\n\n') : '  No further combinations — all prime implicants found in initial grouping.'}

================================================================================
3. PRIME IMPLICANT CHART
================================================================================
${results.chart && results.chart.length > 0 ? `
${'PI'.padEnd(12)} | ${Object.keys(results.chart[0].covers).join(' | ')}
${'-'.repeat(12)}-+-${'-'.repeat(Object.keys(results.chart[0].covers).length * 4)}
${results.chart.map(row => `${row.pi.padEnd(12)} | ${Object.values(row.covers).map(c => c ? ' X' : '  ').join(' | ')}`).join('\n')}` : '  Chart data not available.'}

================================================================================
4. ESSENTIAL & SELECTED PRIME IMPLICANTS
================================================================================
${results.finalTerms && results.finalTerms.length > 0 ? results.finalTerms.map((t, idx) => `
  Term ${idx + 1}: ${t.binary}
    Covers minterms: (${t.terms.join(', ')})`).join('\n') : '  No final terms.'}

================================================================================
5. FINAL MINIMIZED EXPRESSION
================================================================================

  ${mode === 'SOP' ? 'SOP' : 'POS'} Form:
    ${results.expression}

  LaTeX (for report submission):
    ${results.latex || 'N/A'}

================================================================================
6. TRUTH TABLE
================================================================================

${varNames.map(n => n.padEnd(4)).join(' ')} | OUT
${'-'.repeat(varNames.length * 5)}-+-----
${Array.from({ length: totalRows }, (_, i) => {
  const binary = i.toString(2).padStart(variables, '0');
  const isMinterm = minterms.includes(i);
  const isDontCare = dontCares.includes(i);
  const output = isDontCare ? 'X' : (isMinterm ? (mode === 'SOP' ? '1' : '0') : (mode === 'SOP' ? '0' : '1'));
  return `${binary.split('').map(b => b.padEnd(4)).join(' ')}| ${output}`;
}).join('\n')}

================================================================================
Generated by Q-M Logics — Quine-McCluskey Bitmask Engine
================================================================================
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.download = `noctis-lab-report-${mode.toLowerCase()}-${Date.now()}.txt`;
    link.href = url;
    link.click();
    URL.revokeObjectURL(url);
  };

  const exportCircuitImage = (format) => {
    const el = document.querySelector('[data-tutorial="circuit-canvas"] .react-flow__viewport') 
      || document.querySelector('[data-tutorial="circuit-canvas"]');
    if (!el) return;
    const fn = format === 'png' ? toPng : toSvg;
    fn(el, {
      backgroundColor: '#050505',
      pixelRatio: 2,
    }).then((dataUrl) => {
      const link = document.createElement('a');
      link.download = `noctis-circuit-${mode.toLowerCase()}.${format}`;
      link.href = dataUrl;
      link.click();
    }).catch(err => console.error('Export failed:', err));
  };

  return (
    <div className="flex gap-3">
      <button
        onClick={generateLabReport}
        className="flex items-center gap-2 px-4 py-2 glass hover:bg-white/10 transition-colors text-xs font-bold text-white shadow-xl border border-white/10 hover:border-white/20"
      >
        <FileText className="w-3 h-3" /> Lab Report
      </button>
      <button
        onClick={() => exportCircuitImage('png')}
        className="flex items-center gap-2 px-4 py-2 glass hover:bg-white/10 transition-colors text-xs font-bold text-white shadow-xl border border-white/10 hover:border-white/20"
      >
        <Image className="w-3 h-3" /> Circuit PNG
      </button>
    </div>
  );
};
